name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this solve? Why do you need this?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or features you've considered?

  - type: dropdown
    id: module
    attributes:
      label: Related module
      description: Which part of Nerve Agent does this relate to?
      options:
        - Dashboard / Daily Driver
        - Projects
        - Sprint Stack
        - Notes
        - Library
        - Client Portal
        - Time Tracking
        - Agent / AI
        - Settings
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, screenshots, or mockups
